/**
 * Blog posts seed data.
 * Content field uses the same block format as notes (p, h2, list, tip, code).
 */

export const BLOG_POSTS = [
  {
    slug:            'google-l5-data-engineer-interview',
    title:           'My Google L5 Data Engineer Interview Experience — I Got the Offer',
    excerpt:         'Five rounds, three months of prep, and a lot of Kafka. Here\'s exactly what was asked, what tripped me up, and how I finally cracked L5.',
    author_name:     'Arjun Mehta',
    author_initials: 'AM',
    author_color:    '#6366F1',
    category_id:     'interview-experience',
    company:         'Google',
    tags:            ['Google', 'Data Engineering', 'Kafka', 'System Design', 'L5'],
    read_time:       '12 min read',
    is_published:    true,
    is_featured:     true,
    published_at:    '2026-04-20T10:00:00Z',
    content: [
      { type: 'p', text: 'After two previous attempts at Google (L4 in 2022, L4→L5 conversion in 2023), I finally cleared the L5 Data Engineer loop in February 2026. This is the complete breakdown — every round, every question I remember, and the things that actually made the difference.' },
      { type: 'h2', text: 'Background' },
      { type: 'p', text: 'I was a Senior Data Engineer at a Series B fintech, 5 years of experience total. Stack: Spark, Kafka, Airflow, BigQuery. I started prep about 3 months out and focused heavily on system design and Kafka internals since those tripped me up in previous loops.' },
      { type: 'h2', text: 'Interview Structure (5 rounds)' },
      { type: 'list', items: [
        'Round 1 — DSA (45 min): LeetCode Medium/Hard on arrays + graphs',
        'Round 2 — Data Engineering System Design (60 min): Design a real-time pipeline',
        'Round 3 — General System Design (60 min): Design a URL shortener at Google scale',
        'Round 4 — Googliness + Leadership (45 min): Behavioural + project deep dive',
        'Round 5 — Team Match (30 min): Informal chat with potential team lead',
      ]},
      { type: 'h2', text: 'Round 1 — DSA' },
      { type: 'p', text: 'The interviewer jumped straight in. First question: find all islands in a grid (BFS/DFS). Easy warm-up. Then: a modified version of merge intervals where intervals could have priority weights. I solved both but the second one took longer than I\'d have liked.' },
      { type: 'tip', text: 'Google cares more about how you think than the final answer. Talk through your approach before coding. They want structured reasoning, not memorized solutions.' },
      { type: 'h2', text: 'Round 2 — Data Engineering System Design' },
      { type: 'p', text: 'The prompt: "Design a real-time fraud detection pipeline that processes 500K transactions/sec with sub-100ms latency alerts." I started with clarifying questions: What\'s the tolerance for false positives? Is this global or regional? The interviewer was clearly happy — he said most candidates jump straight to architecture.' },
      { type: 'p', text: 'My design: Kafka as the ingestion layer (partitioned by user_id for ordering), Flink for stateful stream processing (feature computation + model scoring), Redis for feature store (low-latency lookups), Cassandra for audit log, PagerDuty/SNS for alert fanout.' },
      { type: 'tip', text: 'For DE system design, always address: exactly-once semantics, late data handling, schema evolution, and operational concerns (monitoring, replay). These are the "hard" parts Google cares about at L5.' },
      { type: 'h2', text: 'Round 4 — Behavioural' },
      { type: 'p', text: '"Tell me about a time you disagreed with your manager", "Describe the most complex system you built end-to-end", "When have you had to make a decision with incomplete information?" I used STAR format and quantified impact throughout.' },
      { type: 'h2', text: 'What Made the Difference This Time' },
      { type: 'list', items: [
        'I read "Designing Data-Intensive Applications" cover to cover — the replication chapter alone saved me in round 2',
        'Did 20 mock system design interviews with a study partner',
        'For every LeetCode problem, I wrote the time/space complexity before running it',
        'Used EngiNotes Kafka deep-dive to understand ISR, HW, exactly-once end-to-end',
      ]},
    ],
  },

  {
    slug:            'kafka-exactly-once-production',
    title:           'How We Achieved Exactly-Once Processing at 500K Events/Sec',
    excerpt:         'After 3 production incidents caused by duplicate payments, we implemented exactly-once Kafka processing end-to-end. Here\'s the full technical story.',
    author_name:     'Priya Sharma',
    author_initials: 'PS',
    author_color:    '#10B981',
    category_id:     'tech-article',
    company:         null,
    tags:            ['Kafka', 'Exactly-Once', 'Transactions', 'Data Engineering'],
    read_time:       '9 min read',
    is_published:    true,
    is_featured:     false,
    published_at:    '2026-04-15T10:00:00Z',
    content: [
      { type: 'p', text: 'In 2025, our payments team had three separate production incidents where customers were double-charged due to duplicate Kafka message processing. Each incident cost us tens of thousands in refunds and damaged customer trust. This is the story of how we fixed it — properly, end-to-end.' },
      { type: 'h2', text: 'Why Duplicates Happened' },
      { type: 'p', text: 'Our original setup: Kafka consumer reads a payment event → calls payment processor API → commits the Kafka offset. The problem: if the process died after calling the payment API but before committing the offset, the message was re-delivered and processed again. We had at-least-once semantics but an idempotent consumer was NOT implemented.' },
      { type: 'h2', text: 'The Fix: Exactly-Once End-to-End' },
      { type: 'p', text: 'True exactly-once in Kafka requires three components working together: idempotent producer (deduplicates retries), transactions (atomic multi-partition commits), and read_committed consumer (only sees committed records). None of these alone is sufficient.' },
      { type: 'tip', text: 'The most common misconception: "I\'ll just make my consumer idempotent." That\'s necessary but not sufficient — you also need idempotent producers and transactional offset commits to prevent any re-processing.' },
      { type: 'h2', text: 'Implementation' },
      { type: 'p', text: 'We use the consume-transform-produce pattern: consume payment events from one topic, validate and enrich, produce to the confirmed-payments topic, and commit both the output and the input offset atomically via sendOffsetsToTransaction(). A crash at any point results in the transaction being aborted — both the output record AND the offset reset, so the message is re-processed from a clean state.' },
      { type: 'h2', text: 'Results' },
      { type: 'list', items: [
        'Zero duplicate payment incidents in 6 months since deployment',
        'Throughput: 500K events/sec with exactly-once — latency increased by ~12ms (acceptable)',
        'Monthly refund cost dropped by ₹2.4 lakhs',
        'Kafka Streams with processing.guarantee=exactly_once_v2 handles the complexity',
      ]},
    ],
  },

  {
    slug:            'from-analyst-to-data-engineer',
    title:           'How I Transitioned from SQL Analyst to Data Engineer in 8 Months',
    excerpt:         'I was a Business Analyst who could write SQL. Eight months later I was building Spark pipelines at a fintech. Here\'s the exact roadmap I followed.',
    author_name:     'Neha Kapoor',
    author_initials: 'NK',
    author_color:    '#F59E0B',
    category_id:     'career',
    company:         null,
    tags:            ['Career Change', 'Data Engineering', 'Learning Path', 'Spark', 'Kafka'],
    read_time:       '7 min read',
    is_published:    true,
    is_featured:     false,
    published_at:    '2026-04-10T10:00:00Z',
    content: [
      { type: 'p', text: 'In January 2025 I was a Business Analyst at a retail company, writing SQL reports for stakeholders and spending half my time in Excel. By September I was a Junior Data Engineer at a fintech building Spark batch pipelines that processed ₹10 crore of transactions daily. This is exactly how I did it.' },
      { type: 'h2', text: 'Month 1-2: Python + SQL Fundamentals' },
      { type: 'p', text: 'I already knew SQL well (it was my job), so I doubled down. Window functions, CTEs, query optimization — I made sure I could answer any SQL interview question cold. For Python, I focused on: data structures, OOP basics, pandas, and writing clean functions. Target: 2 LeetCode easy SQL problems per day.' },
      { type: 'h2', text: 'Month 3-4: Spark + Big Data Concepts' },
      { type: 'p', text: 'I took the "Apache Spark Deep Dive" note on EngiNotes and read it twice. Understanding RDDs, DataFrames, the Catalyst optimizer, and shuffle costs was the biggest mindset shift. I practiced on 10GB public datasets (NYC Taxi, IMDB) using a free Databricks Community Edition cluster.' },
      { type: 'tip', text: 'Don\'t just read about Spark — run jobs. Find a 5-10 GB public dataset and write 10 different transformations. Debug a shuffle problem. Nothing replaces hands-on.' },
      { type: 'h2', text: 'Month 5-6: Kafka + Streaming' },
      { type: 'p', text: 'This was the hardest part for me conceptually. I spent 3 weeks on the Kafka note before the ISR and consumer group concepts clicked. I built a small project: a local Kafka cluster consuming Reddit posts, processing them with Kafka Streams to count post frequencies per hour, and writing results to PostgreSQL.' },
      { type: 'h2', text: 'Month 7-8: Job Search' },
      { type: 'p', text: 'I applied to 40 companies, got 12 phone screens, 5 final rounds, and 2 offers. The projects I built (available on GitHub) made the difference — interviewers could see I could build things, not just talk about them.' },
      { type: 'h2', text: 'The Honest Truth' },
      { type: 'list', items: [
        'I studied 2-3 hours every weekday and 5-6 hours on weekends — this is not a casual transition',
        'The EngiNotes deep-dives (Kafka, Spark) saved me months vs piecing together blog posts',
        'Build real projects — GitHub > certificates every time',
        'Your SQL background is a genuine advantage — most DE candidates are weak at SQL',
      ]},
    ],
  },
]
